**Задача 1.** Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): 

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], 

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. 

Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept)

In [1]:

import numpy as np
import pandas as pnd

zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = len(zp)
n

10

In [2]:
x = zp.reshape([10,1])
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [3]:
y = ks.reshape([10,1])
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [4]:
X = np.hstack([np.ones([10,1]),x])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [5]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),X.T @ y)
B

array([[444.17735732],
       [  2.62053888]])

In [6]:
b1 = (np.mean(zp*ks)-np.mean(zp)*np.mean(ks))/(np.mean(zp**2)-np.mean(zp)**2)
b1

2.620538882402765

In [7]:
b0 = np.mean(ks)-b1*np.mean(zp)
b0

444.1773573243596

In [8]:
y_pred = b0+b1*zp
y_pred

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

In [9]:
y_pred1 = b1*zp
y_pred1

array([ 91.71886088, 117.92424971, 497.90238766, 524.10777648,
       104.8215553 , 183.43772177, 141.50909965, 393.08083236,
       314.46466589, 288.25927706])

In [12]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [13]:
zp=zp.reshape(-1,1)
zp

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [14]:
B = np.dot(np.linalg.inv(np.dot(zp.T,zp)),np.dot(zp.T,ks))
B

array([5.88982042])

In [15]:
regres = model.fit(zp,ks)
print(regres.intercept_)

444.17735732435955


In [16]:
print(regres.coef_)

[2.62053888]


***2. Метод градиентного спуска***

In [17]:

 def mse_(B1,y=y,x=x,n=n):
    return np.sum((B1*x-y)**2)/n

In [19]:
alpha = 1e-6
B1 = 0.1
for i in range (3000):
        B1 -= alpha*(2/n)*np.sum((B1*x-y)*x)
        if i % 500 == 0:
           print ('Interation={i}, B1={B1}, mse={mse}'.format(i=i,B1=B1,mse=mse_(B1)))
           

Interation=0, B1=0.25952808, mse=493237.7212546963
Interation=500, B1=5.889815595583751, mse=56516.858416040064
Interation=1000, B1=5.8898204201285544, mse=56516.85841571941
Interation=1500, B1=5.889820420132673, mse=56516.85841571943
Interation=2000, B1=5.889820420132673, mse=56516.85841571943
Interation=2500, B1=5.889820420132673, mse=56516.85841571943


In [20]:
mse_(5.88982)

56516.85841572182